## This file is ran automatically the first time a Python program imports the package dbdemo
import os

from flask import Flask
from flask_mysqldb import MySQL
from dbdemo.student import student
from dbdemo.grade import grade

## __name__ is the name of the module. When running directly from python, it will be 'dbdemo'
## Outside of this module, as in run.py, it is '__main__' by default
## Create an instance of the Flask class to be used for request routing
app = Flask(__name__)

## configuration of database

# app.config["MYSQL_USER"] = ''
# app.config["MYSQL_PASSWORD"] = ''
# app.config["MYSQL_DB"] = ''
# app.config["MYSQL_HOST"] = ''
# app.config["SECRET_KEY"] = '' ## secret key for sessions (signed cookies). Flask uses it to protect the contents of the user session against tampering.
# app.config["WTF_CSRF_SECRET_KEY"] = '' ## token for csrf protection of forms.
# ## secret keys can be generated by secrets.token_hex()



app.config["MYSQL_USER"] = os.getenv("MYSQL_USER", "demo_user")
app.config["MYSQL_PASSWORD"] = os.getenv("MYSQL_PASSWORD", "demo_pass")
app.config["MYSQL_DB"] = os.getenv("MYSQL_DB", "demo")
app.config["MYSQL_HOST"] = os.getenv("MYSQL_HOST", "db")
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev_secret_key")
app.config["WTF_CSRF_SECRET_KEY"] = os.getenv("WTF_CSRF_SECRET_KEY", "dev_csrf_secret_key")

## initialize database connection object
db = MySQL(app)

## routes must be imported after the app object has been initialized
from dbdemo import routes
from dbdemo.grade import routes
from dbdemo.student import routes
app.register_blueprint(student)
app.register_blueprint(grade)
